name: 'Setup Zig Compiler'
description: 'Download and install the Zig compiler, and cache the global Zig cache'
inputs:
  version:
    description: 'Version of the Zig compiler, e.g. "0.13.0" or "0.13.0-dev.351+64ef45eb0". "master" uses the latest nightly build. "latest" uses the latest tagged release. Leave empty to use minimum_zig_version from build.zig.zon, with a fallback to "latest".'
    default: ''
  mirror:
    description: 'Override of Zig download mirror to use, e.g. "https://pkg.machengine.org/zig".'
    required: false
    default: ''
  use-cache:
    description: 'Whether to cache the global Zig cache directory.'
    required: true
    default: true
  cache-key:
    description: 'Additional cache key component to include when caching the global Zig cache directory. When using a matrix strategy, this should include the matrix variables to ensure all jobs are cached. Matrix variables which decide the OS can be omitted, since the OS is always included in the cache key.'
    required: false
    default: ''
  cache-size-limit:
    description: 'The maximum permitted size of the global Zig cache directory, in MiB. When the cache directory exceeds this size, it is cleared. Default is 2048 (2 GiB). 0 means no limit.'
    required: true
    default: 2048
outputs:
  cache-hit:
    description: 'Whether the Zig global cache was restored from a previous run'
  cache-key-used:
    description: 'The cache key that was used to restore the cache, or "none" if no cache was found'
  zig-version:
    description: 'The resolved Zig version that was installed'
runs:
  using: 'node22'
  main: 'main.js'
  post: 'post.js'
