{
  "name": "check-mirrors",
  "on": {
    "schedule": [
      { "cron": "0 6,18 * * *" },
    ],
    "workflow_dispatch": null,
  },
  "jobs": {
    "check-mirrors": {
      "runs-on": "ubuntu-latest",
      "steps": [
        { "uses": "actions/checkout@v4" },
        {
          "name": "Check mirrors",
          "env": {
            "PUSHOVER_USER": "${{ secrets.PUSHOVER_USER }}",
            "PUSHOVER_TOKEN": "${{ secrets.PUSHOVER_TOKEN }}",
          },
          "run": "sh check-mirrors.sh",
        },
      ],
    },
  },
}
